version: '3'

services:
  app: 
    image: trybe-app
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    container_name: next_postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=0.0.0.0
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    