version: "3"

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    image: trybe-app
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    restart: always
    environment:
      NODE_ENV: production
    links:
      - db
volumes:
  db:
    driver: local